#! /bin/bash

DOMAIN=$1

openssl req \
    -new \
    -newkey rsa:4096 \
    -days 365 \
    -nodes \
    -x509 \
    -subj "/C=US/ST=California/L=Davis/O=$DOMAIN/CN=$DOMAIN" \
    -keyout "$DOMAIN.key" \
    -out "$DOMAIN.cert"
